language: ruby
sudo: false
cache: bundler
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
before_install:
  - gem install bundler -v $(grep -F "BUNDLED WITH" -A 1 "${BUNDLE_GEMFILE:-Gemfile}.lock" | tail -1)
gemfile:
  - gemfiles/rspec_2_x.gemfile
  - gemfiles/rspec_3_0.gemfile
  - gemfiles/rspec_3_1.gemfile
  - gemfiles/rspec_3_2.gemfile
  - gemfiles/rspec_3_3.gemfile
  - gemfiles/rspec_3_4.gemfile
  - gemfiles/rspec_3_5.gemfile
  - gemfiles/rspec_3_6.gemfile
  - gemfiles/rspec_3_7.gemfile
  - gemfiles/rspec_3_8.gemfile
script: bundle exec rspec
